### ISSUE TITLE
关于get_model 函数的疑问

### ISSUE THREAD

**Issue by fangxu622** [Jiangfeng-Xiong/satellite_seg#1]
![image](https://user-images.githubusercontent.com/16681534/38427313-7b8a870e-39eb-11e8-8634-4d4e76e3c31f.png)
这个地方的model 是否为models
但是不论我如何更改都出现了错误
![image](https://user-images.githubusercontent.com/16681534/38427363-9eecf4d4-39eb-11e8-9638-d710546a69fd.png)
 @Jiangfeng-Xiong

**Comment by Jiangfeng-Xiong** [comment]
这里是FCN和SEGNet的部分，之前的代码改得比较乱，然后用了PSPNet就没改了，这里漏了点东西。最新的代码已经更新
