### ISSUE TITLE
关于每个类别的准确率的问题

### ISSUE THREAD

**Issue by DaaaaQi** [Jiangfeng-Xiong/satellite_seg#3]
作者你好，我想请教一下。我利用你的code训练，然后在那0.05部分做验证时，五个类别中，有的准确率能给出来，有的则一直是nan，这是为什么？
不过用最后的模型也可以对测试图片中做分割，效果还可以，能否解答下为什么吗？

**Comment by Jiangfeng-Xiong** [comment]
可能是由于验证集中缺少某类数据，导致计算score的[部分代码](https://github.com/Jiangfeng-Xiong/satellite_seg/blob/master/utils/metrics.py#L25)出现了除数为0的情况，你是有改动代码吗？ @DaaaaQi

**Comment by DaaaaQi** [comment]
也不算是改动代码，就是用新版本的一些句法替代了旧版本的。我是在win10 pycharm下运行的，pytorch1.0.0版本。其实不光是利用val进行验证时有这个问题，就算是用train部分训练，再用train部分验证，也是这样。在用val部分进行验证时，metrics.py中的hist，我观察了label_true和label_pred，发现label_true中是缺少类别的。基本只有类别为1和2的存在，其他都是0。我在想是不是由label_true和label_pred生成hist时出现了问题？ @Jiangfeng-Xiong

**Comment by Jiangfeng-Xiong** [comment]
根据你这么说，那确实是因为label_true中不存在某些类别造成的，可以把[zeros](https://github.com/Jiangfeng-Xiong/satellite_seg/blob/master/utils/metrics.py#L21)改成ones，就不会有NAN的情况，当然不改也其实没事。因为第1类和第2类的样本比较多，数据不均衡，导致采样出的样本某些类别不存在，应该不是其它原因造成的。你可以统计下验证集中样本类别的分布

**Comment by DaaaaQi** [comment]
我还有些疑问，就像我上面说的，我用0.95的部分作训练集，同时也用它作验证集，理论上讲是不是效果应该很好呢？但实际并不是。另外，在验证的时候，是随机取部分label_true进行验证的吧，我在想是不是应该有时候也会取到类别比如为3，4比较多的时候呢，但是我训练时一直观察label_true,发现一直是类别1,2的多，所以3,4准确率输出一直是nan，即便我的训练集和验证集都是0.95的那部分（这应该不会有数据不均衡的问题了？？），还请多指教，感谢。 @Jiangfeng-Xiong

**Comment by DaaaaQi** [comment]
您好。之前我做的实验用的损失函数都是pytorch新版本中更新的torch.nn.functional.crossentropy，它集成了log_softmax和nll_loss。因为我用您原来写的损失函数，就是crossentropy2d的话，在：    log_p = log_p.transpose(1, 2).transpose(2, 3).contiguous().view(-1, c)
    log_p = log_p[target.view(n, h, w, 1).repeat(1, 1, 1, c) >= 0]  这里会报错，我理解的是因为上面的view（-1，c）把log_p改变成2维了，所以下面的target.view（）这里就不能有这么多参数。不知道对不对。我在想是因为损失函数的问题导致分类准确率不好吗？因为我在最新做实验的时候发现1这个类别预测的准确率极其低（train是s1s2数据，val是相应的val）。我需要用您原本写的损失函数来训练吗？那里的view（-1，c）如何修改比价合适呢？希望您能帮帮忙，这个问题确实令我十分困惑，感谢！ @Jiangfeng-Xiong

**Comment by Jiangfeng-Xiong** [comment]
> 您好。之前我做的实验用的损失函数都是pytorch新版本中更新的torch.nn.functional.crossentropy，它集成了log_softmax和nll_loss。因为我用您原来写的损失函数，就是crossentropy2d的话，在： log_p = log_p.transpose(1, 2).transpose(2, 3).contiguous().view(-1, c)
> log_p = log_p[target.view(n, h, w, 1).repeat(1, 1, 1, c) >= 0] 这里会报错，我理解的是因为上面的view（-1，c）把log_p改变成2维了，所以下面的target.view（）这里就不能有这么多参数。不知道对不对。我在想是因为损失函数的问题导致分类准确率不好吗？因为我在最新做实验的时候发现1这个类别预测的准确率极其低（train是s1s2数据，val是相应的val）。我需要用您原本写的损失函数来训练吗？那里的view（-1，c）如何修改比价合适呢？希望您能帮帮忙，这个问题确实令我十分困惑，感谢！ @Jiangfeng-Xiong

你改了损失函数，但只有第一类的准确率不对，应该不是因为损失函数原因引起的，用新版本中的函数没问题，你再找找其他方面原因。因为我写这份代码已经是一年前多了，有些细节记得也不太清楚。

**Comment by DaaaaQi** [comment]
> 您好。之前我做的实验用的损失函数都是pytorch新版本中更新的torch.nn.functional.crossentropy，它集成了log_softmax和nll_loss。因为我用您原来写的损失函数，就是crossentropy2d的话，在： log_p = log_p.transpose(1, 2).transpose(2, 3).contiguous().view(-1, c)
> log_p = log_p[target.view(n, h, w, 1).repeat(1, 1, 1, c) >= 0] 这里会报错，我理解的是因为上面的view（-1，c）把log_p改变成2维了，所以下面的target.view（）这里就不能有这么多参数。不知道对不对。我在想是因为损失函数的问题导致分类准确率不好吗？因为我在最新做实验的时候发现1这个类别预测的准确率极其低（train是s1s2数据，val是相应的val）。我需要用您原本写的损失函数来训练吗？那里的view（-1，c）如何修改比价合适呢？希望您能帮帮忙，这个问题确实令我十分困惑，感谢！ @Jiangfeng-Xiong
> 
> 你改了损失函数，但只有第一类的准确率不对，应该不是因为损失函数原因引起的，用新版本中的函数没问题，你再找找其他方面原因。因为我写这份代码已经是一年前多了，有些细节记得也不太清楚。

恩，好的，我再研究下，非常感谢。
