### ISSUE TITLE
您好，我现在也在参加一个类似的比赛，有些问题想咨询一下您

### ISSUE THREAD

**Issue by NuistZF** [Jiangfeng-Xiong/satellite_seg#6]
我现在是在用UNet跑一个baseline模型，感觉UNet的效果并不是很好，不知道您当时有没有试过UNet，是不是会比PSPNet差了很多效果？

**Comment by Jiangfeng-Xiong** [comment]
unet从被提出到现在已经有挺多改进版本，其实kaggle上挺多分割比赛都还是在用Unet，从效果上看的话，backbone特征网络的选择和数据处理上对结果的影响可能更大点 @NuistZF

**Comment by NuistZF** [comment]
嗯，我感觉我用的最原始版本的UNet是不是不足以应付这个任务，想用您之前用过的PSPNet试一下。不过我在跑代码的时候有个疑问，PSPNet最后输出的图片大小是和经过ResNet之后的特征图大小一样，怎么与和原图大小一样的分割结果做loss？是需要resize一下吗？
